//
// Generated by Microsoft (R) HLSL Shader Compiler 9.30.9200.16384
//
// Parameters:
//
//   float4 ambientColor;
//   float3 cameraPosition;
//   float4 darknessColor;
//   float fogGradientTranslation;
//   float fogScale;
//   float4 lightBackColor;
//   float3 lightDirection;
//   float4 lightFrontColor;
//   float4 materialColor;
//   float3 pointLightColors[16];
//   float4 pointLightPositions[16];
//   float white;
//   float4x4 worldMatrix;
//   float4x4 worldViewMatrix;
//   float4x4 worldViewProjMatrix;
//
//
// Registers:
//
//   Name                   Reg   Size
//   ---------------------- ----- ----
//   pointLightPositions    c0      10
//   pointLightColors       c10     10
//   worldViewProjMatrix    c20      4
//   worldViewMatrix        c24      3
//   worldMatrix            c27      3
//   fogScale               c30      1
//   fogGradientTranslation c31      1
//   materialColor          c32      1
//   lightDirection         c33      1
//   lightFrontColor        c34      1
//   lightBackColor         c35      1
//   cameraPosition         c36      1
//   darknessColor          c37      1
//   ambientColor           c38      1
//   white                  c39      1
//

    vs_3_0
    def c40, -1, -2, -3, -4
    def c41, 0.300000012, 1.20000005, 0, 0
    def c42, 0, 2, -1, 1
    dcl_position v0
    dcl_color v1
    dcl_position o0
    dcl_color o1
    dcl_texcoord o2
    dcl_texcoord1 o3.xyz
    dcl_texcoord2 o4.xyz
    dcl_texcoord3 o5.xyz
    mad r0, v0.xyzx, c42.wwwx, c42.xxxw
    dp4 o0.z, r0, c22
    dp4 r1.w, r0, c23
    rcp r1.z, r1.w
    dp4 r1.x, r0, c20
    mul o2.x, r1.z, r1.x
    dp4 r1.y, r0, c21
    mad o2.y, r1.y, r1.z, c31.x
    mov o0.xyw, r1
    mul r1.x, c30.x, c30.x
    dp4 r2.x, r0, c27
    dp4 r2.y, r0, c28
    dp4 r2.z, r0, c29
    add r0.xyz, -r2, c36
    dp3 r0.w, r0, r0
    mul r1.yz, r0.xxyw, r0.xxyw
    mov o5.xyz, r0
    add r0.x, r1.z, r1.y
    mul o2.zw, r0.xywx, r1.x
    mov r0.x, c42.x
    slt r0.y, r0.x, c1.w
    mul r0.z, c32.w, v1.w
    add r1, c40, v0.w
    sge r1, -r1_abs, r1_abs
    mad r3.xyz, r1.w, c42.xxyw, c42.xxzw
    add r4.xyz, -r3.yyzw, c42.xzxw
    mad r3.xyz, r1.z, r4, r3
    lrp r4.xyz, r1.y, c42.xwxw, r3
    lrp r3.xyz, r1.x, c42.zxxw, r4
    sge r0.w, -v0_abs.w, v0_abs.w
    lrp r1.xyz, r0.w, c42.wxxw, r3
    dp3 r3.x, r1, c27
    dp3 r3.y, r1, c28
    dp3 r3.z, r1, c29
    nrm r4.xyz, r3
    dp3 r0.w, r4, c33
    max r0.w, r0.w, c42.x
    mov r3.xyz, c34
    mad r3.xyz, r0.w, r3, c38
    dp3 r0.w, r4, -c33
    max r0.w, r0.w, c42.x
    mad r3.xyz, r0.w, c35, r3
    slt r0.w, r0.x, c0.w
    add r5.xyz, r2, -c0
    dp3 r1.w, r5, r5
    rsq r2.w, r1.w
    mul r5.xyz, r2.w, r5
    dp3 r2.w, r4, r5
    mul r2.w, r2.w, c40.w
    max r2.w, r2.w, c41.x
    min r2.w, r2.w, -c40.x
    mul r3.w, c0.w, c0.w
    rcp r3.w, r3.w
    mul r1.w, r1.w, r3.w
    min r1.w, r1.w, -c40.x
    add r1.w, -r1.w, -c40.x
    mul r1.w, r1.w, r1.w
    mul r1.w, r2.w, r1.w
    mul r5.xyz, r1.w, c10
    mul r5.xyz, r0.w, r5
    mad r3.xyz, r3, r0.z, r5
    add r5.xyz, r2, -c1
    dp3 r0.z, r5, r5
    rsq r0.w, r0.z
    mul r5.xyz, r0.w, r5
    dp3 r0.w, r4, r5
    mul r0.w, r0.w, c40.w
    max r0.w, r0.w, c41.x
    mul r1.w, c1.w, c1.w
    rcp r1.w, r1.w
    mul r0.z, r0.z, r1.w
    min r0.zw, r0, -c40.x
    add r0.z, -r0.z, -c40.x
    mul r0.z, r0.z, r0.z
    mul r0.z, r0.w, r0.z
    mul r5.xyz, r0.z, c11
    mad r0.yzw, r0.y, r5.xxyz, r3.xxyz
    slt r1.w, r0.x, c2.w
    add r3.xyz, r2, -c2
    dp3 r2.w, r3, r3
    rsq r3.w, r2.w
    mul r3.xyz, r3.w, r3
    dp3 r3.x, r4, r3
    mul r3.x, r3.x, c40.w
    max r3.x, r3.x, c41.x
    min r3.x, r3.x, -c40.x
    mul r3.y, c2.w, c2.w
    rcp r3.y, r3.y
    mul r2.w, r2.w, r3.y
    min r2.w, r2.w, -c40.x
    add r2.w, -r2.w, -c40.x
    mul r2.w, r2.w, r2.w
    mul r2.w, r3.x, r2.w
    mul r3.xyz, r2.w, c12
    mad r0.yzw, r1.w, r3.xxyz, r0
    slt r1.w, r0.x, c3.w
    add r3.xyz, r2, -c3
    dp3 r2.w, r3, r3
    rsq r3.w, r2.w
    mul r3.xyz, r3.w, r3
    dp3 r3.x, r4, r3
    mul r3.x, r3.x, c40.w
    max r3.x, r3.x, c41.x
    min r3.x, r3.x, -c40.x
    mul r3.y, c3.w, c3.w
    rcp r3.y, r3.y
    mul r2.w, r2.w, r3.y
    min r2.w, r2.w, -c40.x
    add r2.w, -r2.w, -c40.x
    mul r2.w, r2.w, r2.w
    mul r2.w, r3.x, r2.w
    mul r3.xyz, r2.w, c13
    mad r0.yzw, r1.w, r3.xxyz, r0
    slt r1.w, r0.x, c4.w
    add r3.xyz, r2, -c4
    dp3 r2.w, r3, r3
    rsq r3.w, r2.w
    mul r3.xyz, r3.w, r3
    dp3 r3.x, r4, r3
    mul r3.x, r3.x, c40.w
    max r3.x, r3.x, c41.x
    min r3.x, r3.x, -c40.x
    mul r3.y, c4.w, c4.w
    rcp r3.y, r3.y
    mul r2.w, r2.w, r3.y
    min r2.w, r2.w, -c40.x
    add r2.w, -r2.w, -c40.x
    mul r2.w, r2.w, r2.w
    mul r2.w, r3.x, r2.w
    mul r3.xyz, r2.w, c14
    mad r0.yzw, r1.w, r3.xxyz, r0
    slt r1.w, r0.x, c5.w
    add r3.xyz, r2, -c5
    dp3 r2.w, r3, r3
    rsq r3.w, r2.w
    mul r3.xyz, r3.w, r3
    dp3 r3.x, r4, r3
    mul r3.x, r3.x, c40.w
    max r3.x, r3.x, c41.x
    min r3.x, r3.x, -c40.x
    mul r3.y, c5.w, c5.w
    rcp r3.y, r3.y
    mul r2.w, r2.w, r3.y
    min r2.w, r2.w, -c40.x
    add r2.w, -r2.w, -c40.x
    mul r2.w, r2.w, r2.w
    mul r2.w, r3.x, r2.w
    mul r3.xyz, r2.w, c15
    mad r0.yzw, r1.w, r3.xxyz, r0
    slt r1.w, r0.x, c6.w
    add r3.xyz, r2, -c6
    dp3 r2.w, r3, r3
    rsq r3.w, r2.w
    mul r3.xyz, r3.w, r3
    dp3 r3.x, r4, r3
    mul r3.x, r3.x, c40.w
    max r3.x, r3.x, c41.x
    min r3.x, r3.x, -c40.x
    mul r3.y, c6.w, c6.w
    rcp r3.y, r3.y
    mul r2.w, r2.w, r3.y
    min r2.w, r2.w, -c40.x
    add r2.w, -r2.w, -c40.x
    mul r2.w, r2.w, r2.w
    mul r2.w, r3.x, r2.w
    mul r3.xyz, r2.w, c16
    mad r0.yzw, r1.w, r3.xxyz, r0
    slt r1.w, r0.x, c7.w
    add r3.xyz, r2, -c7
    dp3 r2.w, r3, r3
    rsq r3.w, r2.w
    mul r3.xyz, r3.w, r3
    dp3 r3.x, r4, r3
    mul r3.x, r3.x, c40.w
    max r3.x, r3.x, c41.x
    min r3.x, r3.x, -c40.x
    mul r3.y, c7.w, c7.w
    rcp r3.y, r3.y
    mul r2.w, r2.w, r3.y
    min r2.w, r2.w, -c40.x
    add r2.w, -r2.w, -c40.x
    mul r2.w, r2.w, r2.w
    mul r2.w, r3.x, r2.w
    mul r3.xyz, r2.w, c17
    mad r0.yzw, r1.w, r3.xxyz, r0
    slt r1.w, r0.x, c8.w
    add r3.xyz, r2, -c8
    add r2.xyz, r2, -c9
    dp3 r2.w, r3, r3
    rsq r3.w, r2.w
    mul r3.xyz, r3.w, r3
    dp3 r3.x, r4, r3
    mul r3.x, r3.x, c40.w
    max r3.x, r3.x, c41.x
    min r3.x, r3.x, -c40.x
    mul r3.y, c8.w, c8.w
    rcp r3.y, r3.y
    mul r2.w, r2.w, r3.y
    min r2.w, r2.w, -c40.x
    add r2.w, -r2.w, -c40.x
    mul r2.w, r2.w, r2.w
    mul r2.w, r3.x, r2.w
    mul r3.xyz, r2.w, c18
    mad r0.yzw, r1.w, r3.xxyz, r0
    slt r0.x, r0.x, c9.w
    dp3 r1.w, r2, r2
    rsq r2.w, r1.w
    mul r2.xyz, r2.w, r2
    dp3 r2.x, r4, r2
    mul r2.x, r2.x, c40.w
    max r2.x, r2.x, c41.x
    min r2.x, r2.x, -c40.x
    mul r2.y, c9.w, c9.w
    rcp r2.y, r2.y
    mul r1.w, r1.w, r2.y
    min r1.w, r1.w, -c40.x
    add r1.w, -r1.w, -c40.x
    mul r1.w, r1.w, r1.w
    mul r1.w, r2.x, r1.w
    mul r2.xyz, r1.w, c19
    mad r0.xyz, r0.x, r2, r0.yzww
    max r0.xyz, r0, c42.x
    min r0.xyz, r0, c41.y
    add r2.xyz, -r0, -c40.x
    mul r0.xyz, r0, v1
    mul r0.xyz, r0, c32
    mad r0.xyz, c37, r2, r0
    add r2.xyz, -r0, -c40.x
    mad o1.xyz, c39.x, r2, r0
    dp3 r0.x, r1, c24
    dp3 r0.y, r1, c25
    dp3 r0.z, r1, c26
    nrm r1.xyz, r0
    add o3.xyz, r1, r1
    mov o1.w, v1.w
    mov o4.xyz, c33

// approximately 240 instruction slots used
