//
// Generated by Microsoft (R) HLSL Shader Compiler 9.30.9200.16384
//
// Parameters:
//
//   float alpha;
//   float4 fogColor;
//   float shininess;
//   float4 skyColor1;
//   float4 skyColor2;
//
//
// Registers:
//
//   Name         Reg   Size
//   ------------ ----- ----
//   skyColor1    c0       1
//   skyColor2    c1       1
//   fogColor     c2       1
//   alpha        c3       1
//   shininess    c4       1
//

    ps_3_0
    def c5, -0.600000024, 2.5, 0.600000024, 3
    def c6, 1.5, -0.0250000004, 1, 2
    def c7, 10, 5, 0.159154937, 0.5
    def c8, 6.28318548, -3.14159274, 0.300000012, 1
    def c9, 0.800000012, 0.200000003, 0.75, 0
    dcl_color v0.xyz
    dcl_texcoord v1
    dcl_texcoord1 v2.xy
    mul r0.x, c5.z, v1.y
    mov_sat r0.x, r0.x
    mul r0.y, r0.x, r0.x
    mul r0.z, r0.y, c5.w
    dp2add r0.x, r0.y, -r0.x, r0.z
    mov r1.xyz, c0
    add r0.yzw, -r1.xxyz, c1.xxyz
    mad r0.xyz, r0.x, r0.yzww, c0
    mad_sat r0.w, v1.y, c6.w, c6.z
    mul r1.w, r0.w, r0.w
    mul r2.x, r1.w, c5.w
    dp2add r0.w, r1.w, -r0.w, r2.x
    mov r2.x, c9.x
    mul r2.xyz, r2.x, c2
    mad r1.xyz, r1, c9.y, r2
    lrp r2.xyz, r0.w, r0, r1
    add r0.x, c5.x, v1.w
    mul_sat r0.x, r0.x, c5.y
    mul r0.y, r0.x, r0.x
    mul r0.z, r0.y, c5.w
    dp2add r0.x, r0.y, -r0.x, r0.z
    mul r0.x, r0.x, r0.x
    mad_sat r0.y, v1.z, c6.x, c6.y
    add r0.y, -r0.y, c6.z
    mad r0.y, r0.y, -r0.y, c6.z
    mul r0.y, r0.y, c9.z
    lrp r1.xyz, r0.y, c2, v0
    lrp r3.xyz, r0.x, r2, r1
    mov r0.xy, v1
    dp2add r0.x, r0.yxzw, c7, v2.y
    add r0.x, r0.x, v2.x
    mad r0.x, r0.x, c7.z, c7.w
    frc r0.x, r0.x
    mad r0.x, r0.x, c8.x, c8.y
    sincos r1.x, r0.x
    mad r0.x, r1.x, c8.z, c8.w
    mul r0.xyz, r0.x, r3
    cmp oC0.xyz, -c4.x, r3, r0
    mov oC0.w, c3.x

// approximately 50 instruction slots used
