//
// Generated by Microsoft (R) HLSL Shader Compiler 9.30.9200.16384
//
// Parameters:
//
//   float4 fogColor;
//   float4 skyColor1;
//   float4 skyColor2;
//
//
// Registers:
//
//   Name         Reg   Size
//   ------------ ----- ----
//   skyColor1    c0       1
//   skyColor2    c1       1
//   fogColor     c2       1
//

    ps_3_0
    def c3, 0.600000024, 3, 2, 1
    def c4, 0.800000012, 0.200000003, 0, 0
    dcl_texcoord v0.y
    mad_sat r0.x, v0.y, c3.z, c3.w
    mul r0.y, r0.x, r0.x
    mul r0.z, r0.y, c3.y
    dp2add r0.x, r0.y, -r0.x, r0.z
    mul_sat r0.y, c3.x, v0.y
    mul r0.z, r0.y, r0.y
    mul r0.w, r0.z, c3.y
    dp2add r0.y, r0.z, -r0.y, r0.w
    mov r1.xyz, c0
    add r2.xyz, -r1, c1
    mad r0.yzw, r0.y, r2.xxyz, c0.xxyz
    mov r2.x, c4.x
    mul r2.xyz, r2.x, c2
    mad r1.xyz, r1, c4.y, r2
    add r0.yzw, r0, -r1.xxyz
    mad oC0.xyz, r0.x, r0.yzww, r1
    mov oC0.w, c3.w

// approximately 19 instruction slots used
