//
// Generated by Microsoft (R) HLSL Shader Compiler 9.30.9200.16384
//
// Parameters:
//
//   float4 fogColor;
//   float4 skyColor1;
//   float4 skyColor2;
//
//
// Registers:
//
//   Name         Reg   Size
//   ------------ ----- ----
//   skyColor1    c0       1
//   skyColor2    c1       1
//   fogColor     c2       1
//

    ps_3_0
    def c3, -0.5, 1, 0.600000024, 3
    def c4, 2, 1, 0.800000012, 0.200000003
    def c5, 0, -0.5, 0.600000024, 1
    def c6, 9.99999975e-005, 0.800000012, 0, 0
    def c7, 0, 2, 10, 0
    dcl_color v0.zw
    dcl_texcoord v1.yz
    dcl_texcoord2 v2.xyz
    dcl_texcoord3 v3.xyz
    mul_sat r0.x, c3.z, v1.y
    mul r0.y, r0.x, r0.x
    mul r0.z, r0.y, c3.w
    dp2add r0.x, r0.y, -r0.x, r0.z
    mov r1.xyz, c0
    add r0.yzw, -r1.xxyz, c1.xxyz
    mad r0.xyz, r0.x, r0.yzww, c0
    mad_sat r0.w, v1.y, c4.x, c4.y
    mul r1.w, r0.w, r0.w
    mul r2.x, r1.w, c3.w
    dp2add r0.w, r1.w, -r0.w, r2.x
    mov r2.z, c4.z
    mul r2.xyz, r2.z, c2
    mad r1.xyz, r1, c4.w, r2
    lrp r2.xyz, r0.w, r0, r1
    add r0.xyz, c7.xxyw, v2
    dp3 r0.w, r0, r0
    rsq r0.w, r0.w
    dp3 r1.x, v3, v3
    rsq r1.y, r1.x
    mad oC0.w, r1.x, c6.x, c6.y
    mul r1.xyz, r1.y, v3
    mad r0.xyz, r0, r0.w, r1
    dp3 r0.x, r0, r0
    rsq r0.x, r0.x
    mul_sat r0.x, r0.x, r0.z
    pow r1.x, r0.x, c7.z
    mul r0.x, r1.x, v0.w
    mul r0.xyz, r0.x, c0
    add r1.xy, c3.yxzw, v1.yzzw
    mov_sat r1.x, r1.x
    add_sat r0.w, r1.y, r1.y
    mad r1.xyz, r1.x, c5.xyxw, c5.xzww
    mad r0.xyz, v0.z, r1, r0
    mov_sat r1.x, v1.z
    lrp r3.xyz, r1.x, c2, r0
    add r0.xyz, r2, -r3
    mad oC0.xyz, r0.w, r0, r3

// approximately 42 instruction slots used
