//
// Generated by Microsoft (R) HLSL Shader Compiler 9.30.9200.16384
//
// Parameters:
//
//   float4 skyColor1;
//   float4 skyColor2;
//
//
// Registers:
//
//   Name         Reg   Size
//   ------------ ----- ----
//   skyColor1    c0       1
//   skyColor2    c1       1
//

    ps_3_0
    def c2, 1, -0.800000012, -1, 0.800000012
    def c3, 0.25, 1, 1.25, 0
    dcl_color v0.xyz
    dcl_texcoord v1.yz
    add_sat r0.x, c2.x, v1.y
    mov r1.xyz, c1
    mov_sat r0.yz, v1.xzyw
    lrp r2.xyz, r0.z, r1, c0
    add r2.xyz, r2, c2.yzzw
    mad r0.xzw, r0.x, r2.xyyz, c2.wyxx
    mul r2.xyz, c3.xxyw, v0
    mad r1.xyz, v0, -c3.xxyw, r1
    mul r1.w, r0.y, c3.z
    min r2.w, r1.w, c2.x
    mad r1.xyz, r2.w, r1, r2
    mul r1.w, r0.y, r0.y
    mul r1.w, r0.y, r1.w
    lrp r2.xyz, r1.w, r0.xzww, r1
    cmp oC0.xyz, -r0.y, r1, r2
    mov oC0.w, c2.x

// approximately 16 instruction slots used
