//
// Generated by Microsoft (R) HLSL Shader Compiler 9.30.9200.16384
//
// Parameters:
//
//   float4 fogColor;
//   float4 skyColor1;
//   float4 skyColor2;
//
//
// Registers:
//
//   Name         Reg   Size
//   ------------ ----- ----
//   skyColor1    c0       1
//   skyColor2    c1       1
//   fogColor     c2       1
//

    ps_3_0
    def c3, 1, 0.600000024, 3, 2
    def c4, 0.800000012, 0.200000003, 0, 0
    dcl_color v0
    dcl_texcoord v1.yz
    mul_sat r0.x, c3.y, v1.y
    mul r0.y, r0.x, r0.x
    mul r0.z, r0.y, c3.z
    dp2add r0.x, r0.y, -r0.x, r0.z
    mov r1, c0
    add r2, -r1, c1
    mad r0, r0.x, r2, c0
    mad_sat r2.x, v1.y, c3.w, c3.x
    mul r2.y, r2.x, r2.x
    mul r2.z, r2.y, c3.z
    dp2add r2.x, r2.y, -r2.x, r2.z
    mov r3.x, c4.x
    mul r3, r3.x, c2
    mad r1, r1, c4.y, r3
    lrp r3, r2.x, r0, r1
    add r0, r3, -v0
    mov_sat r1.x, v1.z
    mul r1.y, r1.x, r1.x
    mul r1.y, r1.y, r1.y
    mad r1.x, r1.y, -r1.x, c3.x
    mad r1.x, r1.x, -r1.x, c3.x
    mad oC0, r1.x, r0, v0

// approximately 24 instruction slots used
