//
// Generated by Microsoft (R) HLSL Shader Compiler 9.30.9200.16384
//
// Parameters:
//
//   float4x4 MaskMatrix;
//   float4x4 NormalMatrix;
//   float4x4 Proj;
//   float4x4 TextureMatrix;
//   float4x4 WorldView;
//   float aaOffset;
//   float4 baseColor;
//   float2 deformedWidgetPos;
//   float2 deformedWidgetSize;
//   float4x4 inverseWidgetBindMatrix;
//   float4x4 widgetBindMatrix;
//   float2 widgetBindPos;
//   float2 widgetBindSize;
//   bool widgetDeformationEnabled;
//
//
// Registers:
//
//   Name                     Reg   Size
//   ------------------------ ----- ----
//   widgetDeformationEnabled b0       1
//   Proj                     c0       4
//   WorldView                c4       4
//   widgetBindMatrix         c8       4
//   inverseWidgetBindMatrix  c12      4
//   MaskMatrix               c16      2
//   TextureMatrix            c18      2
//   NormalMatrix             c20      2
//   widgetBindPos            c22      1
//   widgetBindSize           c23      1
//   deformedWidgetPos        c24      1
//   deformedWidgetSize       c25      1
//   aaOffset                 c26      1
//   baseColor                c27      1
//

    vs_3_0
    def c28, -1, 1, 0, 9.99999975e-006
    def c29, 0.699999988, 0.5, -0.135000005, 0
    dcl_position v0
    dcl_color v1
    dcl_texcoord v2
    dcl_texcoord1 v3
    dcl_texcoord2 v4
    dcl_position o0
    dcl_color o1
    dcl_texcoord o2.xy
    dcl_texcoord1 o3.xy
    if b0
      dp4 r0.x, v0, c8
      dp4 r0.y, v0, c9
      dp4 r1.z, v0, c10
      dp4 r1.w, v0, c11
      slt r0.zw, r0.xyxy, c22.xyxy
      mov r2.xy, c22
      add r2.xy, r2, c23
      slt r2.xy, r0, r2
      add r2.zw, r0.xyxy, -c22.xyxy
      rcp r3.x, c23.x
      mad r2.z, r2.z, r3.x, c28.x
      mad r2.x, r2.x, r2.z, c28.y
      mad r3.x, r0.z, -r2.x, r2.x
      rcp r0.z, c23.y
      mad r0.z, r2.w, r0.z, c28.x
      mad r0.z, r2.y, r0.z, c28.y
      mad r3.y, r0.w, -r0.z, r0.z
      add r0.xy, r0, c24
      add r0.xy, r0, -c22
      mov r2.xy, c23
      add r0.zw, -r2.xyxy, c25.xyxy
      mad r1.xy, r3, r0.zwzw, r0
      dp4 r0.x, r1, c12
      dp4 r0.y, r1, c13
      dp4 r0.z, r1, c14
      dp4 r0.w, r1, c15
    else
      mov r0, v0
    endif
    dp4 r1.x, r0, c4
    dp4 r1.y, r0, c5
    dp4 r1.z, r0, c6
    dp4 r2.w, r0, c7
    mul o1, c27, v1
    mul r3.xy, v2, v2
    add r1.w, r3.y, r3.x
    slt r1.w, c28.z, r1.w
    mul r3.xy, v3, v3
    add r3.x, r3.y, r3.x
    slt r3.x, c28.z, r3.x
    mul r1.w, r1.w, r3.x
    mul r3.xyz, c28.yyzw, v2.xyxw
    dp3 r4.x, r3, c20
    dp3 r4.y, r3, c21
    mul r3.xyz, c28.yyzw, v3.xyxw
    dp3 r5.x, r3, c20
    dp3 r5.y, r3, c21
    mov r4.z, c28.z
    dp3 r3.x, r4, r4
    mov r5.z, c28.z
    dp3 r3.z, r5, r5
    slt r3.yw, c28.z, r3.xxzz
    mul r3.y, r3.w, r3.y
    rsq r3.x, r3.x
    rcp r3.x, r3.x
    add r3.x, r3.x, c28.w
    rcp r3.x, r3.x
    mul r4.xyz, r3.x, r4
    rsq r3.x, r3.z
    rcp r3.x, r3.x
    add r3.x, r3.x, c28.w
    rcp r3.x, r3.x
    mad r3.xzw, r5.xyyz, r3.x, r4.xyyz
    dp3 r4.w, r3.xzww, r3.xzww
    rsq r4.w, r4.w
    rcp r4.w, r4.w
    add r4.w, r4.w, c28.w
    rcp r4.w, r4.w
    mul r3.xzw, r3, r4.w
    dp3 r4.x, r4, r3.xzww
    max r4.x, r4.x, c29.x
    rcp r4.x, r4.x
    mul r4.x, r4.x, c26.x
    mul r4.yzw, r3.xxzw, r4.x
    mad r5.xyz, r3.xzww, r4.x, r1
    add r5.w, r5.z, c29.y
    add r3.xzw, -r1.xyyz, r5.xyyw
    mul r4.xyz, r3.y, r4.yzww
    mul r3.xyz, r3.xzww, r3.y
    mad r0.xyz, r1.w, r4, r0
    mad r1.xyz, r1.w, r3, r1
    add r2.xyz, r1, c29.zzww
    dp4 o0.x, r2, c0
    dp4 o0.y, r2, c1
    dp4 o0.z, r2, c2
    dp4 o0.w, r2, c3
    dp4 o2.x, r0, c16
    dp4 o2.y, r0, c17
    mad r0.xyz, v4.xyxw, c28.yyzw, c28.zzyw
    dp3 o3.x, r0, c18.xyww
    dp3 o3.y, r0, c19.xyww

// approximately 94 instruction slots used
