//
// Generated by Microsoft (R) HLSL Shader Compiler 9.30.9200.16384
//
// Parameters:
//
//   int filter;
//   sampler2D maskSampler;
//   float textureBrightness;
//   float textureContrast;
//   bool textureEnabled;
//   float textureOpacity;
//   sampler2D textureSampler;
//   float textureSaturation;
//
//
// Registers:
//
//   Name              Reg   Size
//   ----------------- ----- ----
//   textureEnabled    b0       1
//   filter            c0       1
//   textureOpacity    c1       1
//   textureBrightness c2       1
//   textureContrast   c3       1
//   textureSaturation c4       1
//   maskSampler       s0       1
//   textureSampler    s1       1
//

    ps_3_0
    def c5, -1, 0.300000012, 0.589999974, 0.109999999
    def c6, 0.5, 0, -1, -2
    dcl_color v0
    dcl_texcoord v1.xy
    dcl_texcoord1 v2.xy
    dcl_2d s0
    dcl_2d s1
    if b0
      texld r0, v2, s1
      mov r1.x, c5.x
      add r1.y, r1.x, c4.x
      dp3 r1.z, c5.yzww, r0
      add r1.w, -r1.x, -c4.x
      add r2.xyz, -r0, r1.z
      mad r2.xyz, r1.w, r2, r0
      cmp r1.yzw, -r1_abs.y, r0.xxyz, r2.xxyz
      add r2.x, r1.x, c2.x
      mul r2.yzw, r1, c2.x
      cmp r1.yzw, -r2_abs.x, r1, r2
      add r2.x, r1.x, c3.x
      add r1.x, -r1.x, -c3.x
      add r2.yzw, -r1, c6.x
      mad r2.yzw, r1.x, r2, r1
      cmp r1.xyz, -r2_abs.x, r1.yzww, r2.yzww
      min r0.xyz, r1, -c5.x
      mad r0, v0, r0, -v0
      mad r0, c1.x, r0, v0
    else
      mul r0, c3.x, v0
    endif
    mov r1.yzw, c6
    if_eq c0.x, r1.y
      mov oC0, r0
    else
      texld r2, v1, s0
      rcp r1.x, r2.w
      mul r3.xyz, r1.x, r2
      cmp r2.xyz, -r2.w, r2, r3
      add r1.xy, r1.zwzw, c0.x
      add r3.xyz, -r0, r2
      mov r3.w, c6.y
      mad r3, r2.w, r3, r0
      mul r2, r0, r2
      mov r0.w, r2.w
      cmp r0, -r1_abs.y, r2, r0
      cmp oC0, -r1_abs.x, r3, r0
    endif

// approximately 44 instruction slots used (2 texture, 42 arithmetic)
