//
// Generated by Microsoft (R) HLSL Shader Compiler 9.30.9200.16384
//
// Parameters:
//
//   float4x4 Proj;
//
//
// Registers:
//
//   Name         Reg   Size
//   ------------ ----- ----
//   Proj         c0       4
//

    vs_3_0
    def c4, -0.135000005, 0, 0, 0
    dcl_position v0
    dcl_color v1
    dcl_texcoord2 v2
    dcl_position o0
    dcl_color o1
    dcl_texcoord o2.xy
    add r0, c4.xxyy, v0
    dp4 o0.x, r0, c0
    dp4 o0.y, r0, c1
    dp4 o0.z, r0, c2
    dp4 o0.w, r0, c3
    mov o1, v1
    mov o2.xy, v2

// approximately 7 instruction slots used
