//
// Generated by Microsoft (R) HLSL Shader Compiler 9.30.9200.16384
//
// Parameters:
//
//   sampler2D textureSampler;
//
//
// Registers:
//
//   Name           Reg   Size
//   -------------- ----- ----
//   textureSampler s0       1
//

    ps_3_0
    dcl_color v0
    dcl_texcoord v1.xy
    dcl_2d s0
    texld r0, v1, s0
    rcp r1.x, r0.w
    mul r1.xyz, r0, r1.x
    cmp r0.xyz, -r0.w, r0, r1
    mul oC0, r0, v0

// approximately 5 instruction slots used (1 texture, 4 arithmetic)
