//
// Generated by Microsoft (R) HLSL Shader Compiler 9.30.9200.16384
//
// Parameters:
//
//   sampler2D textureSampler;
//   float2 textureScale;
//
//
// Registers:
//
//   Name           Reg   Size
//   -------------- ----- ----
//   textureScale   c0       1
//   textureSampler s0       1
//

    ps_3_0
    def c1, 2, 0.5, 0.25, 0
    dcl_color v0
    dcl_texcoord v1.xy
    dcl_2d s0
    rcp r0.z, c0.x
    rcp r0.w, c0.y
    mul r0.xy, r0.zwzw, v1
    frc r0.zw, r0.xyxy
    add r0.xy, -r0.zwzw, r0
    mad r0.xy, r0, c1.x, c1.y
    mul r1.zw, r0.xyxy, c0.xyxy
    mad r1.xy, r0, c0, c0
    texld r0, r1.zwzw, s0
    texld r2, r1.xwzw, s0
    texld r3, r1.zyzw, s0
    texld r1, r1, s0
    add r0, r0, r2
    add r0, r3, r0
    add r0, r1, r0
    mul r1, r0, c1.z
    rcp r0.x, r1.w
    mul r0.xyz, r0.x, r1
    cmp r1.xyz, -r0.w, r1, r0
    mul oC0, r1, v0

// approximately 20 instruction slots used (4 texture, 16 arithmetic)
