//
// Generated by Microsoft (R) HLSL Shader Compiler 9.30.9200.16384
//
// Parameters:
//
//   sampler2D textureSampler;
//   float2 textureScale;
//
//
// Registers:
//
//   Name           Reg   Size
//   -------------- ----- ----
//   textureScale   c0       1
//   textureSampler s0       1
//

    ps_3_0
    def c1, 4, 0.5, 2, 3
    def c2, 0.0625, 0, 0, 0
    dcl_color v0
    dcl_texcoord v1.xy
    dcl_2d s0
    rcp r0.z, c0.x
    rcp r0.w, c0.y
    mul r0.xy, r0.zwzw, v1
    frc r0.zw, r0.xyxy
    add r0.xy, -r0.zwzw, r0
    mad r0.xy, r0, c1.x, c1.y
    mul r1.xw, r0.xyzy, c0.xyzy
    mad r1.yz, r0.xyxw, c0.xyxw, c0.xyxw
    texld r0, r1.xwzw, s0
    texld r2, r1.zwzw, s0
    add r0, r0, r2
    mov r2.zw, r1.xywy
    mov r3.xy, c0
    mad r2.xy, r3, c1.z, r1.xwzw
    texld r4, r2.xzzw, s0
    add r0, r0, r4
    mad r3.xy, r3, c1.w, r1.xwzw
    mov r3.zw, r2
    texld r4, r2.xwzw, s0
    texld r5, r3.xzzw, s0
    texld r6, r3.xwzw, s0
    add r0, r0, r5
    texld r5, r1, s0
    texld r7, r1.zyzw, s0
    add r0, r0, r5
    add r0, r7, r0
    add r0, r4, r0
    add r0, r6, r0
    mov r1.y, r2.y
    texld r4, r1, s0
    add r0, r0, r4
    texld r4, r1.zyzw, s0
    mov r5.xz, r1
    add r0, r0, r4
    texld r4, r2, s0
    mov r5.w, r2.x
    add r0, r0, r4
    mov r1.w, r3.x
    texld r1, r1.wyzw, s0
    add r0, r0, r1
    mov r5.y, r3.y
    texld r1, r3, s0
    texld r2, r5, s0
    texld r3, r5.zyzw, s0
    texld r4, r5.wyzw, s0
    add r0, r0, r2
    add r0, r3, r0
    add r0, r4, r0
    add r0, r1, r0
    mul r1, r0, c2.x
    rcp r0.x, r1.w
    mul r0.xyz, r0.x, r1
    cmp r1.xyz, -r0.w, r1, r0
    mul oC0, r1, v0

// approximately 54 instruction slots used (16 texture, 38 arithmetic)
