//
// Generated by Microsoft (R) HLSL Shader Compiler 9.30.9200.16384
//
// Parameters:
//
//   float blurScale;
//   sampler2D textureSampler;
//
//
// Registers:
//
//   Name           Reg   Size
//   -------------- ----- ----
//   blurScale      c0       1
//   textureSampler s0       1
//

    ps_2_0
    def c1, 4, 3, 0.0900000036, 0.0500000007
    def c2, 2, 0.119999997, 0.150000006, 0.180000007
    dcl t0.xy
    dcl_2d s0
    mov r0.xy, c1
    mad r1.y, c0.x, -r0.y, t0.y
    mov r1.x, t0.x
    mad r2.y, c0.x, -r0.x, t0.y
    mov r2.x, t0.x
    mov r3.w, c2.x
    mad r3.y, c0.x, -r3.w, t0.y
    mov r3.x, t0.x
    add r4.y, t0.y, -c0.x
    mov r4.x, t0.x
    add r5.y, t0.y, c0.x
    mov r5.x, t0.x
    mad r6.y, c0.x, r3.w, t0.y
    mov r6.x, t0.x
    mad r7.y, c0.x, r0.y, t0.y
    mov r7.x, t0.x
    mad r0.y, c0.x, r0.x, t0.y
    mov r0.x, t0.x
    texld r1, r1, s0
    texld r2, r2, s0
    texld r3, r3, s0
    texld r4, r4, s0
    texld r8, t0, s0
    texld r5, r5, s0
    texld r6, r6, s0
    texld r7, r7, s0
    texld r0, r0, s0
    mul r1, r1, c1.z
    mad r1, r2, c1.w, r1
    mad r1, r3, c2.y, r1
    mad r1, r4, c2.z, r1
    mad r1, r8, c2.w, r1
    mad r1, r5, c2.z, r1
    mad r1, r6, c2.y, r1
    mad r1, r7, c1.z, r1
    mad r0, r0, c1.w, r1
    mov oC0, r0

// approximately 37 instruction slots used (9 texture, 28 arithmetic)
