//
// Generated by Microsoft (R) HLSL Shader Compiler 9.30.9200.16384
//
// Parameters:
//
//   float blurScale;
//   sampler2D textureSampler;
//
//
// Registers:
//
//   Name           Reg   Size
//   -------------- ----- ----
//   blurScale      c0       1
//   textureSampler s0       1
//

    ps_3_0
    def c1, 4, 3, 0.0900000036, 0.0500000007
    def c2, 2, 0.119999997, 0.150000006, 0.180000007
    dcl_texcoord v0.xy
    dcl_2d s0
    mov r0.xy, c1
    mad r1.xy, c0.x, -r0, v0.x
    mov r1.z, v0.y
    texld r2, r1.yzzw, s0
    texld r1, r1.xzzw, s0
    mul r2, r2, c1.z
    mad r1, r1, c1.w, r2
    mov r2.x, c2.x
    mad r3.x, c0.x, -r2.x, v0.x
    mov r3.yw, v0.y
    texld r4, r3, s0
    mad r1, r4, c2.y, r1
    add r3.z, -c0.x, v0.x
    texld r3, r3.zwzw, s0
    mad r1, r3, c2.z, r1
    texld r3, v0, s0
    mad r1, r3, c2.w, r1
    add r3.x, c0.x, v0.x
    mov r3.yw, v0.y
    texld r4, r3, s0
    mad r1, r4, c2.z, r1
    mad r3.z, c0.x, r2.x, v0.x
    texld r2, r3.zwzw, s0
    mad r1, r2, c2.y, r1
    mad r0.xy, c0.x, r0.yxzw, v0.x
    mov r0.z, v0.y
    texld r2, r0.xzzw, s0
    texld r0, r0.yzzw, s0
    mad r1, r2, c1.z, r1
    mad oC0, r0, c1.w, r1

// approximately 30 instruction slots used (9 texture, 21 arithmetic)
